### ISSUE TITLE
Render Top Menu using magento API data

### ISSUE THREAD

**Issue by sergy-gzh** [deity-io/falcon#132]
**Describe the bug**
Given version of falcon is using predefined structure for top navigation

**To Reproduce**
1. Install vanilla magento without sample data.
2. Go to falcon website.
3. Top Navigation is there, should be empty.
**Expected behavior**
Top navigation should reflect real categories from magento

Use already existing in Magento API endpoint for it:
`V1/menu`
It will provide list of menu items with the following data format
`[
    {
        "name": "Mannen",
        "id": 0,
        "url": "http://127.0.0.1:8062/mannen.html",
        "has_active": false,
        "is_active": false,
        "level": 0,
        "is_first": true,
        "is_last": true,
        "position_class": "nav-1",
        "children": []
    }
]`

**Comment by cane-lagerwaard** [comment]
Similar to `falcon-magento2-development` https://github.com/deity-io/falcon-magento2-development/issues/22
