### ISSUE TITLE
Error accessing product page (custom Magento store)

### ISSUE THREAD

**Issue by leon0v** [deity-io/falcon#147]
**Describe the bug**
After succesfully setting up a Magento + Deity PWA locally with the [project generator](https://github.com/deity-io/falcon/tree/master/packages/create-falcon-app) and with the default (https://magento.deity.io/) backend Magento store, I tried to connect to my own Magento store. Connecting was no problem, and the products showed correctly on the home page. But when I tried to click on a product to go to the product page, an error showed. This is probably fairly easy to solve, but i find it pretty hard to debug. So I have got two questions:

- Someone knows the problem here?
- Some tips on debugging requests from front end to server, and from server to Magento backing store.

**To Reproduce**
1. Set up Deity falcon project with the [project generator](https://github.com/deity-io/falcon/tree/master/packages/create-falcon-app).
2. Change the magento store in the default.json config file to your own.
3. Try to visit a product page

**Expected behavior**
Get to the product page

**Screenshots**
![image](https://user-images.githubusercontent.com/17271164/48209125-ac3a1800-e374-11e8-841a-2e4536b64674.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/17271164/48209274-00dd9300-e375-11e8-9d01-998af4f415ad.png)

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
None

**Comment by Borales** [comment]
Hi @leon0v! Thank you for your bug report. 
We found what is causing this problem, we'll fix this as soon as possible.

**Comment by Borales** [comment]
@leon0v the problem is here - https://github.com/deity-io/falcon/blob/master/packages/falcon-magento2-api/src/index.js#L408-L418

Looks like your locally created product does not have any `customAttributes` set, so GQL tries to get SEO fields from a non-existing `seo` field, which has to be set at least with a `null` value if `customAttributes` is empty.

**Comment by KirillStativka** [comment]
HI ! @Borales , have some news regarding this fix? i have same issue .

**Comment by Borales** [comment]
@KirillStativka Hi. The fix is being reviewed
