### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#175]
* [x] Provide translation mechanism with high DX.
I think that we need to use components provided via `react-i18next`. After an investigation, it looks like `<NamespacesConsumer>` will do the job. Moreover, it does not make sense to write custom components which will base on `react-i18next` API/internals as these will be rewritten completely to support react hooks only
* [ ] Translate all outstanding texts.
* [x] Fix issue with translation code splitting
    - translations are split but i18next initial state is not initialized correctly

**Comment by tutok** [comment]
I think we need to have at least 2 components:
 * `<I18n />` - will render i18next instance. 
    renderProp function looks like `(I18n: I18next.I18n) => any`
  
    here is an example of  `<I18n />` usage, it shows how to change language:
    ```
    <I18n>{i18n => <LanguageSwitcher languages={languages} onChange={x => i18n.changeLanguage(x.code)} />}</I18n>
    ```

 * `<T />` - provide access to `translationFunction` 
    renderProp function looks like `(t: I18next.translateFunction) => any`
    component could receive all `I18next.translateFunction` which will be passed down as defaultoptions into translate function returned from `<T/>` component.

    examples of usages:
    to render translated string
    ```
    <p><T id="some.translation.key" /></p>
   // -> <p>Some translated key</p>
    ```
    to render translated string (with pluralization)
    ```
    <p><T id="some.translation.key" count={2} /></p>
   // -> <p>Some translated keys</p>
    ```

    translation key can be provided as children, and it is equivalent to above, but I am not sure if this syntax should be available, I am getting more convinced to disallow this
   ```
    <p><T count={2}>some.translation.key</T></p>
   // -> <p>Some translated keys</p>
   ```
   
    to get access to transaltionFunction you need to render children as function
   ```
    <T>
      {t => (
        <form>
          <Group>
            <Input
              type="email"
              required
              height="lg"
              aria-label={t('newsletter.emailPlaceholder')}
              placeholder={t('newsletter.emailPlaceholder')}
            />
            <Button as="input" type="submit" value={t('newsletter.subscribe')} flex="none" />
          </Group>
        </form>
      )}
    </T>
   ```

    to get access to transaltionFunction with predefined translation options you need to provide translation options as attributes, same like above when translationg `key`
    ```
    <T returnObjects>
      {t =>
        t('newCustomer.benefitsList').map((x: string) => (
          <ListItem key={x}>
            <Icon src="check" />
            {x}
          </ListItem>
        ))
      }
    </T>

    // translations.json
    {
      "newCustomer": {
        "benefitsList": ["check out faster", "keep more than one address", "track orders and more"],
      }
    }
   ```
   `returnObject` is `I18next.transalteFunction` option which allows to return transaltions as object, it is usefull when we would like to get more than one translated string at once (like in above example)


After that, I am start thinking about introducing one more component, called let say `<Translate />` which will always render translated strings via renderProps. Simply I would like to simplify above example and make it more verbose:

``` 
  <Translate key="newCustomer.benefitsList" >
    {t => // here t is string[] instade of transaltionFunction
        t.map(x => (
          <ListItem key={x}>
            <Icon src="check" />
            {x}
          </ListItem>
        ))
      }
  <Translate/>
```

**Comment by Borales** [comment]
@tutok 

>  <p><T count={2}>some.translation.key</T></p>
you're right, that doesn't look "natural". 

What about translation templates?
For example something like - `{product} has {n} products left in stock`, how it will look like with `<T>`?

**Comment by Borales** [comment]
@tutok sorry, github is messing around, I was referring to this one:

> `<p><T count={2}>some.translation.key</T></p>`

**Comment by tadeuszwojcik** [comment]
(disclaimer: only my opinion, it's not a request to change anything as a must)

I'm not sure about `returnObjects` API, it would make translations json file sort of source of truth of the UI, bit like poor man CMS. I'd prefer to explicitly ask for things via keys from translations, so I'd personally skip that API.

I'd only expose one single `<Trans(late)>` component, that would do what you've described in point **2.** and when `<Trans>` get used via render prop API I'd expose (merged point **3.** and **4.**):
```js
<Trans>
  {(t, i18n) => ...}
</Trans>
```
so i18n is set as a second param.

When we'd have hooks support we could depreciate point **2.**  potentially(?) and add following hook (we'd still keep render prop as class components do not get hooks):
```js
const { t, i18n } = useTranslations(); // or similar
```

**Comment by tutok** [comment]
I think that merging `<I18n>` with `<T>` (functionality from point **3.**) is good idea, but maybe name i18n will be better? as we getting `i18next` instance actually (`t` is function of `i18next`)

```
<i18n>
  {(t, i18n) => ...}
</i18n>
```

but I am not sure about disallowing `returnObjects` option, as it is quite handy when it comes to rendering the list of strings.
