### ISSUE TITLE
Falcon Logger

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#20]
Logger needs to be improved:

- [x] Send information to a 3rd-party tracking system
- [ ] Support browser and server modes
- [x] Improve formatting
- [x] trace calls to external services
- [x] log them to standard output
- [x] json output

**Comment by Borales** [comment]
https://getpino.io

**Comment by cane-lagerwaard** [comment]
* trace calls to external services
* log them to standard output

**Comment by tutok** [comment]
resolved by https://github.com/deity-io/falcon/pull/471
