### ISSUE TITLE
Revalidate offline mode

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#266]
**Describe the bug**
Inconsistent offline mode

**To Reproduce**
1. Go to https://latest.snapshot.deity.io/
2. Enable "offline" mode
3. Refresh the page

**Comment by tutok** [comment]
https://stackoverflow.com/questions/51031445/apollo-offline-first-support-service-worker-or-persisted-cache
https://github.com/GoogleChrome/workbox/issues/1620

**Comment by Borales** [comment]
Seems like we need to revalidate it again.
After a few tests - it looks like only the first page gets cached, the rest is ignored.

Steps to reproduce (snapshot):
- Clear every cache, unregister SW
- close snapshot tab
- open any random snapshot page (product or category)
- visit a few more pages
- go offline
- check visited pages
- only the first visited page will be served in offline mode

**Comment by Borales** [comment]
@cane-lagerwaard seems like it was a random bug, I cannot reproduce it anymore. It works as expected, closing this ticket.
