### ISSUE TITLE
redirect to origin url does not work with SSR

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#267]
**What should be changed/improved?**
It looks like redirecting the user to `origin` URL after sign-in does not work if `ProtectedRoute` will be rendered on the server side (SSR) 
It works when that redirection will be done on the client side (in web browser).

The reason is we are using [location state](https://github.com/deity-io/falcon/blob/45fb8719d7cd61ae73bc5bffdff67ce297185bee/packages/falcon-ecommerce-uikit/src/Router/ProtectedRoute.tsx#L25) to keep `origin` URL while that state is not returned with response from SSR. 

**Your suggested solution**
The easiest solution will be to add `origin=` query string param instead.

**Comment by Borales** [comment]
@tutok please consider using `returnTo` or `returnUrl` for query string param name.

**Comment by mateuszwozniak** [comment]
Or just `next` as it doesn't have to return to the previous url in all cases.
