### ISSUE TITLE
Dynamic main menu

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#275]
**Is your feature request related to a problem? Please describe.**
Menu rendered in Navbar is taken from the hardcoded configuration file, which causes that it needs to be synchronized with Magento manually. 

**Describe the solution you'd like**
add graphQL query resolver for `/rest/default/V1/menu` Magento endpoint and use that Query to make Navbar content dynamic.

**Comment by cane-lagerwaard** [comment]
Just Main menu, leave other menu's i.e. footer as it is right now - using config files
