### ISSUE TITLE
Cannot load site — GraphQL error on category query

### ISSUE THREAD

**Issue by natewoodbridge** [deity-io/falcon#279]
**Describe the bug**
When I try to run any category GraphQL query (such as the below), am I getting the error: `FalconServer: TypeError: response.data.items.map is not a function at Magento2Api.categoryProducts (/server/node_modules/@deity/falcon-magento2-api/src/index.js:109:34)`

I am linked up to https://magento.deity.io/

```
{
  category(id: "2") {
    products {
      items {
        id
        name
      }
    }
  } 
}
```

I am using 
```
    "@deity/falcon-magento2-api": "^0.2.0",
    "@deity/falcon-server": "^0.1.1",
```

Downgrading to 2.2.7 seems to fix this. I believe the query response for categories does not include items any more.

**Comment by mateuszwozniak** [comment]
We have added `products` field to `category` query in the last release so the newest code should handle that without problems. Can you please try to generate a new app via `npx create-falcon-app your_app_name` and see if that works correctly? That will use the newest version of both `falcon-magento2-api` and `falcon-server`.

**Comment by Borales** [comment]
Closing this issue, if the issue still remains - please feel free to re-open it again
