### ISSUE TITLE
Overriding UI components

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon#287]
Research/investigate current issues

**Comment by tutok** [comment]
# Asumptions
* we would like continue spreading the code between packages

# Solutions which does not sound good
* webpack aliases - each component in e.g. `falcon-ui` needs to have its own alias. sound strange
* webpack resolution - will introduce a lot of mess, will downgrade to `deity-core`

# Solutions which we definitely need to consider
* module replacement
   * [NormalModuleReplacementPlugin](https://webpack.js.org/plugins/normal-module-replacement-plugin/), [src](https://github.com/webpack/webpack/blob/master/lib/NormalModuleReplacementPlugin.js) 
   * [webpack-dependency-injector](https://github.com/sonybinhle/webpack-dependency-injector)
   * [path-override-webpack-plugin](https://www.npmjs.com/package/path-override-webpack-plugin)

* module rewiring
   * [babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire)

## module replacement
I have played with this technique, mostly with `NormalModuleReplacementPlugin` as it is inspiration for `webpack-dependency-injector`, and it looks like it allows to replace any kind of module. 
For example, I managed to replace even underlying components like `<Text>` in entire dependency chain  (`shop-with-blog` -> `falcon-ecommerce-uikit` -> `falcon-ui`) via configuration located in single place.

NormalModuleReplacementPlugin provide handler with two main args: 
* `request` - requested module, relative path (exactly the same value as used in import/require)
* `context` - requesting module.

We replace modules, so it will be useful if our code base be organized according to component-per-module pattern. In case where module about to replace exports couple of components all of them needs to be exported from new module.

Right now exported modules are unique inside specific package - we need to follow that pattern!

Names of exports needs to be in sync between old and new module

We need to think about api which allows to replace module in specific package - it should be possible to do with `context` property. Lets say, `falcon-ui` and `falcon-ecommerce-uikit` export diffren from implementation perspecitve but named in same way  `Text` module, I believe, we should be able to replace `Text` module only from `falcon-ui` for example. Without checking context, it will replaced everywhere. 

HMR is supported!

webpack aliases are supported! this means that it is possible to use them when specyfing paths to modules which should be resolved, e.g. alias `src`

configuration could looks like this:
```
    override({
        '@deity/falcon-ui': {
            'Text': 'src/components/MyNewFancyText',
            // other modules to override
        },
        // definitions for another package
    })
```

**Comment by tutok** [comment]
How it was implemented? Open `falcon-client.build.config.js`, then edit `moduleOverride` dictionary:

```
module.exports = {
  moduleOverride: {
    '@deity/falcon-ui/dist/components/Text': 'src/components/RedText'
  }
};
```
above configuration will tell falcon-client to use RedText component located in example project everywhere where falcon-ui's Text component is used, including other packages e.g. @deity/falcon-ecommerce-uikit
