### ISSUE TITLE
IE11 bind bug

### ISSUE THREAD

**Issue by brightonmike** [deity-io/falcon#293]
**Describe the bug**
In IE11, a a JS error breaks Falcon.

**To Reproduce**
1. Run the server in production mode
2. Build the client and run in production mode
3. Observe broken JS functionality in IE11

**Expected behavior**
In IE11, functionality should be comparable to other browsers.

```
SCRIPT5007: Unable to get property 'bind' of undefined or null reference
vendors.1796c3c3.chunk.js (9,169993)
```

 - Windows 10
 - IE11

**Comment by cane-lagerwaard** [comment]
Thanks for the feedback @brightonmike. We're looking into this
