### ISSUE TITLE
yarn start server crashes when doing a hard reload

### ISSUE THREAD

**Issue by RicardoDeity** [deity-io/falcon#294]
**Describe the bug**
I am using the falcon app with .scss files in the React components. When i start my falcon app with the command `yarn start` everything is okay. If there's a js error which is solved so that the app rebuilds, my app isn't correctly reloaded.  Sometimes when i refresh a page with i.e. CTRL + R, the app also breaks. My javascript and my styles aren't loaded anymore. Only some basic styles are visible. No logging in the console is been done except for the message that the app is running (green log line).
Seems to be an issue when .scss is introduced in the falcon app.

**To Reproduce**
1. Create a falcon app with .scss files imported in the components 
2. Start the app with `yarn start`
3. Refresh the site with CTRL + R or create a JS error and fix it to reload the site

**Expected behavior**
My app should reload with all styles and javascript intact.

**Desktop (please complete the following information):**
 - MacOS Mojave
 - Chrome
 - Version 71.0

**Additional context**
You can checkout the deity corporate repo to reproduce the problem.

**Comment by leon0v** [comment]
I've got a similar issue. Using *.module.scss files, first couple of changes the HMR works fine. Then all of the sudden the HMR doesn't seem to work anymore. When I then refresh the page, there is no styling from scss files applied at all. No errors in browser console or client console.

**Comment by tutok** [comment]
I tried to reproduce this error, and I can not. After some digging, I found issue reported on  `react` https://github.com/facebook/react/issues/14502, which is really simillar to ours (problem with clearing react context).
Above issue is already solved by https://github.com/facebook/react/pull/14706 and released in `react@16.8.3` which is installed in latest `falcon-client` on `dev`  branch
