### ISSUE TITLE
Service worker is not being registered in Chrome

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon#297]
**Describe the bug**
Apps built with Falcon 0.3 seem to not register a service worker in Google Chrome (no specific version) but they do register in Firefox

**To Reproduce**
1. Open Chrome dev tools
2. Go to "Application" -> "Service workers"
3. Note there is no SW registered

**Expected behavior**
Service worker should get registered 

**Desktop (please complete the following information):**
Tested on browserstack:

 - OS: macOS & W10
 - Browser: Chrome
 - Version 70+

**Comment by Borales** [comment]
@cane-lagerwaard please specify the mode (dev or prod) and https (on/off). This is required to reproduce the env you have.

**Comment by cane-lagerwaard** [comment]
@Borales prod and https, please check demo.deity.io and deity.io (deity.cloud seems to work)

**Comment by Borales** [comment]
@cane-lagerwaard it works fine for me. Although, if you manually unregister it - you need to perform "empty cache and hard reload" (push and hold "reload" button). So every new visitor gets SW by default.

<img width="846" alt="screenshot 2019-02-03 at 21 51 38" src="https://user-images.githubusercontent.com/1118933/52182519-45ef5500-27fe-11e9-9bdc-6ef057b0ed24.png">

**Comment by cane-lagerwaard** [comment]
@Borales try on a machine that hasn't visited the website before

**Comment by cane-lagerwaard** [comment]
@Borales After doing clear storage and empty cache and reload, nothing there:

 ![image.png](https://images.zenhubusercontent.com/5bc9eac631854f160a8b5fe8/53d6d385-4c60-482c-91c0-9c5d717baff6)

**Comment by tutok** [comment]
@cane-lagerwaard and when you expand `Service workers from other domains`, the list is also empty?

**Comment by tutok** [comment]
hmm, lighthouse PWA score is really poor, and it confirms SW issue
![image](https://user-images.githubusercontent.com/1831641/52184685-780cb100-2816-11e9-8cc5-fc906733f358.png)

**Comment by cane-lagerwaard** [comment]
> @cane-lagerwaard and when you expand `Service workers from other domains`, the list is also empty?

No, it contains Service workers from other domains :)
