### ISSUE TITLE
installation error falcon server

### ISSUE THREAD

**Issue by deity-bram** [deity-io/falcon#300]
**Describe the bug**
After a clean install "npm create falcon-app" the server cant start due to following error 

[nodemon] starting `node index.js`
Uncaught Exception:  { Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/my-app/server/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
[nodemon] clean exit - waiting for changes before restart

**To Reproduce**
1. Go to 'command prompt'
2. Type  'yarn create falcon-app my-app '
3. Go to the server folder  
4. Type "yarn start"

**Expected behavior**
The server to become availible

**Desktop(please complete the following information):**
 - Ubuntu 18.0.4

**Comment by borriglione** [comment]
I think this is connected to the `core-js` package required by the `apollo-env` - module.

In my local installation of `node_modules/apollo-env/package.json` there is:
```
"dependencies": {
    "core-js": "^3.0.0-beta.3",
  },
```
which installed `"core-js@3.0.0-beta.10"` on my local machine which works fine and includes:
`node_modules/apollo-env/node_modules/core-js/proposals/array-flat-and-flat-map.js`

On our dev-server `"core-js@3.0.0-beta.13"` was installed doesn't contain the file:
`node_modules/apollo-env/node_modules/core-js/proposals/array-flat-and-flat-map.js`

**Comment by cane-lagerwaard** [comment]
hi @borriglione we've released a hotfix today which should solve this issue

**Comment by borriglione** [comment]
Thanks @cane-lagerwaard 

Hotfix worked, but only after using `yarn install`. 
`npm install` doesn't support `resolution`-handle in `package.json`
