### ISSUE TITLE
Caching scenarios research

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon#321]
- Research/investigation

**Comment by Borales** [comment]
To be completely agnostic - we cannot rely on any specific backend, therefore we have to provide caching functionality within Falcon packages.

Currently, Falcon-Server supports 3 cache providers by default (out of the box):
- `InMemoryLRUCache` (in-memory app cache)
- `Memcached` (persist)
- `Redis` (persist)

## Step 0: Provide simple cache (time-limited)

Falcon's `ApiDataSource` must be revisited (`ContextHTTPCache`) and cache must be allowed for usage. For GET requests - enable short cache by default (can be disabled via request context, for example - skip cache for fetching cart items). 

## Step 1: Control the cache via GraphQL Schema directives (`@cache`)

- using `@cache` directive for precise cache control and ability to set cache settings per extension/type/field (partial GQL schema)
- for the proper cache invalidation - we have to add/set `ID` field type in GQL Schema to the apropriate field (`Product.sku: ID`)

> Using `@cacheControl` (http-cache) is risky in this context, once the data is cached - there's no way to refresh the cache until it's expired.

## Step 2: Cache the data on an API DataSource Level

- provide "tags" cache dependency (auto-generated from GQL `ID` field and GQL type name)
- callback-dependency for the cache (for example - checking request headers or making a call to an external DB, global state etc). After placing an order - flush the cache for the specific products (by tags)

**Comment by mateuszwozniak** [comment]
I think assumptions here are correct. We just need to create a simple roadmap for all the features so maybe we should first list all the things that need to be done.
