### ISSUE TITLE
GraphQL error: Cannot read property 'quoteId' of undefined

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#334]
**Describe the bug**
When proceeding checkout, I can not accept the Shipping address step as I get the error:

```
GraphQL error: Cannot read property 'quoteId' of undefined
```

`falcon-server` log:
```
FalconServer: TypeError: Cannot read property 'quoteId' of undefined at Magento2Api.performCartAction ([...]\falcon\packages\falcon-magento2-api\src\index.js:1637:15)Cannot read property 'quoteId' of
 undefined
```

1. open `http://localhost:3000/`
2. you should have an already old unauthorized session, with some product in the cart
3. go to checkout and proceed 

**Expected behavior**
proceed checkout without errors

**Desktop (please complete the following information):**
 - OS: windows 10 pro (build 17134.590)
 - Browser: chrome 72.0.3626.119

**Additional context**
I think it happened because I had in cart product which was already out of stock. I added it a couple of hours before I started checkout so someone else could buy the last piece in the meantime.
I think it is worth to check in the first place if that scenario is handled.

**Comment by Borales** [comment]
Seems like it was a one-time issue, cannot reproduce it
