### ISSUE TITLE
Default store for Magento2ApiBase should not be mandatory

### ISSUE THREAD

**Issue by cebesoft** [deity-io/falcon#341]
Falcon server runs into an error if magento has no store view with code "default".

error: FalconServer: TypeError: Cannot read property 'locale' of undefined at Api.fetchBackendConfig (/home/node/app/node_modules/@deity/falcon-magento2-api/src/Magento2ApiBase.js:74:90)Cannot read property 'locale' of undefined

Steps to reproduce:

1. Rename default storeview to some other value, e.g. "samplestore"
2. Set "storePrefix" to "samplestore" in falcon server api configuration
3. Browse the store frontend
4. Error is seen in the falcon server logs and frontend results in error page

The error occurs in falcon-magento2-api/src/Magento2ApiBase.js on line 74:

`this.magentoConfig.defaultLocale = activeStoreConfigs.find(x => x.code === 'default').locale;`

Instead of using the hardcoded 'default' string, the configured "storePrefix" should be used, to avoid the error.

Btw.: what is the defaultLocale used for? Makes no sense for me in magento environment.

**Comment by mateuszwozniak** [comment]
Good find. It turned out that `defaultLocale` is a leftover from old code, so it should be removed.
