### ISSUE TITLE
Missing/invalid translations on "Account" section

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#363]
[http://localhost:3000/account/orders](http://localhost:3000/account/orders) - missing human-readable "status"

<img width="540" alt="Screenshot 2019-03-19 at 20 28 19" src="https://user-images.githubusercontent.com/1118933/54635921-93a9df00-4a85-11e9-9058-aece40bd4097.png">

http://localhost:3000/account/orders/X - invalid "Payment method" value (duplicate of "delivery method")

<img width="323" alt="Screenshot 2019-03-19 at 20 31 01" src="https://user-images.githubusercontent.com/1118933/54636098-f00cfe80-4a85-11e9-9667-19f2fa5a098b.png">

**Comment by nimobeeren** [comment]
I was able to fix the value for "Payment method" (see my PR).

However, I was unable to reproduce the issue with order status. After placing an order and visiting http://localhost:3000/account/orders, the order status shows as "Pending". Looking at the source of hte `OrderListItem` component and translations, I would expect the status to always be either "Pending" or "N/A". Could you check if this issue persists and if so, provide some steps to reproduce?

**Comment by Borales** [comment]
This issue is still valid (on `dev`). Place an order (while being authenticated):

<img width="268" alt="Screenshot 2019-10-15 at 12 50 39" src="https://user-images.githubusercontent.com/1118933/66825397-7c16d400-ef4a-11e9-9b61-4752bd069a38.png">

@nimobeeren did you submit that fix as a PR?

**Comment by nimobeeren** [comment]
@Borales could you confirm order status is NOT being rendered correctly for you?

Payment method is indeed wrong again, seems like a regression.

**Comment by Borales** [comment]
@nimobeeren sorry, I made a typo, "Order status **IS** being rendered correctly".

So it's only Payment method left
