### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [deity-io/falcon#370]
Hello, i am a graphic designer who loves to contribute logos to open source projects. Do you need a logo for this project or any of your other projects?

**Comment by cane-lagerwaard** [comment]
Hi @dee-y Thanks for your offer! Please note that we already have a logo for this project, but nevertheless, you're absolutely free to propose something new. Just keep in mind we cannot guarantee it will be used :)

**Comment by mateuszwozniak** [comment]
@cane-lagerwaard there's no update on that for more than 3 weeks - can we close this?

**Comment by cane-lagerwaard** [comment]
@dee-y do you have any update for us? :)
