### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by LogimaeCommerce** [deity-io/falcon#375]
Hi!

How should the nginx configuration for falcon look like?

Currently my setup for client is

        location / {
                proxy_pass http://localhost:3001/;
        }

but I'm not sure how it should look like for server which is running on port 4000?

<img width="1351" alt="Screenshot 2019-03-28 at 14 13 11" src="https://user-images.githubusercontent.com/48867557/55134427-b57d2300-5163-11e9-9017-295a1a7e3a0e.png">

and is the starter pack supposed to look like this? I think perhaps something with my configuration is blocking images on category view as they are perfectly showing when clicking on products.

Great project, thanks!

**Comment by mateuszwozniak** [comment]
Hi @LogimaeCommerce!

Port 3001 is by default the port of the dev server, so you should rather use port 3000. It doesn't really matter on which port you run the app - it's just a matter of passing that port in the nginx config file.

We use something similar to the following configuration:
```
upstream falcon-client {
    server 127.0.0.1:3000;
}

upstream falcon-server {
    server 127.0.0.1:4000;
}

server {
    listen 80;
    server_name testserver.com;

    location / {
        proxy_pass         http://falcon-client;
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
    }
}

server {
    listen 80;
    server_name api.testserver.com;

    location / {
        proxy_pass         http://falcon-server;
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
    }
}
```

In that case we have `http://testserver.com` that runs frontend (passing requests to `http://127.0.0.1:3000`) and `http://api.testserver.com` that runs backend (passing requests to `http://127.0.0.1:4000`).

Also, as you can see we use `upstream`s because we're testing various domains/subdomains/ports configuration so it's easier to change just the definition of the upstream and all the domains pick up those changes automatically. In the simple setup where you have one domain you can use `http://127.0.0.1:3000` and `http://127.0.0.1:4000` directly without using `upstream`s.

**Comment by LogimaeCommerce** [comment]
> Hi @LogimaeCommerce!
> 
> Port 3001 is by default the port of the dev server, so you should rather use port 3000. It doesn't really matter on which port you run the app - it's just a matter of passing that port in the nginx config file.
> 
> We use something similar to the following configuration:
> 
> ```
> upstream falcon-client {
>     server 127.0.0.1:3000;
> }
> 
> upstream falcon-server {
>     server 127.0.0.1:4000;
> }
> 
> server {
>     listen 80;
>     server_name testserver.com;
> 
>     location / {
>         proxy_pass         http://falcon-client;
>         proxy_set_header   X-Forwarded-For $remote_addr;
>         proxy_set_header   Host $http_host;
>     }
> }
> 
> server {
>     listen 80;
>     server_name api.testserver.com;
> 
>     location / {
>         proxy_pass         http://falcon-server;
>         proxy_set_header   X-Forwarded-For $remote_addr;
>         proxy_set_header   Host $http_host;
>     }
> }
> ```
> In that case we have `http://testserver.com` that runs frontend (passing requests to `http://127.0.0.1:3000`) and `http://api.testserver.com` that runs backend (passing requests to `http://127.0.0.1:4000`).
> 
> Also, as you can see we use `upstream`s because we're testing various domains/subdomains/ports configuration so it's easier to change just the definition of the upstream and all the domains pick up those changes automatically. In the simple setup where you have one domain you can use `http://127.0.0.1:3000` and `http://127.0.0.1:4000` directly without using `upstream`s.

Many thanks! I ran yarn start inside folders "client & server", and so from my experience with vue-storefront I would use the storefront on 3000 and the api on 8080, hence the configuration would be:

```
        location / {
                proxy_pass http://localhost:3000/;
        }

        location /assets/ {
                proxy_pass http://localhost:3000/assets/;
        }

    location /api/ {
                proxy_pass http://localhost:8080/api/;
        }

    location /img/ {
                proxy_pass http://localhost:8080/img/;
        }
```

So your answer was just what i was looking for, thanks again!
