### ISSUE TITLE
Unable to start client in CFA generated application (Windows 10)

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon#389]
**Describe the bug**
When generating the application with create-falcon-app I'm unable to start the client

**To Reproduce**
1. Generate application with CFA
2. Start client
3. See error

**Error output**
```
ERROR in ./node_modules/@deity/falcon-adyen-plugin/dist/AdyenCCPlugin.js
Module not found: Error: Can't resolve 'adyen-cse-web' in 'C:\Users\name\Desktop\test\client\node_modules\@deity\falcon-adyen-plugin\dist'
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Node: v11.0.0

**Additional context**
Tried with other Windows 10 systems and it seems to be working correctly, this might be an edge case. On this system it seems like it doesn't install `adyen-cse-web` at all.

**Comment by tutok** [comment]
I followed reproduction steps and everything looks ok on my end. Package `adyen-cse-web` was installed.

* OS: Win 10
* Node: 10.11.0

**Comment by cane-lagerwaard** [comment]
> I followed reproduction steps and everything looks ok on my end. I was able to do checkout and proceed with payment. (Package `adyen-cse-web` was installed)
> 
> * OS: Win 10
> * Node: 10.11.0

@tutok does it also work on node v11?

**Comment by tutok** [comment]
it works also on node 11:
* OS: Win 10
* Node: 11.13.0

**Comment by mateuszwozniak** [comment]
@Borales if I remember correctly you've seen that error last week. Do you remember what was the issue?

**Comment by Borales** [comment]
@mateuszwozniak @cane-lagerwaard @tutok 
Matt's right, I had a similar issue while deploying to one of the servers (linux-based).
I had exactly the same error, but it was quickly resolved by re-installing the dependencies and regenerating lock file (yarn). @cane-lagerwaard could you try this?

**Comment by cane-lagerwaard** [comment]
@Borales sure I'll try that, thanks
