### ISSUE TITLE
After successful checkout user is not able to pick his address when trying to do another checkout

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon#399]
**Describe the bug**
If you try to go through the checkout twice (without website reload) then you won't be able to select shipping/billing address from your address book during second checkout process. 

**To Reproduce**
1. Log in
2. Make sure that you have at least one address in your address book 
3. Add something to cart
4. Go to checkout (you can see that shipping and billing sections display address picker with your addresses)
5. Finalize purchase
6. Add new thing to the cart
7. Go to checkout page - there's no address picker in shipping and billing sections - you have to provide new address

**Expected behavior**
You should be able to pick shipping and billing address from your addresses

**Comment by tutok** [comment]
I am not sure it is connected to this issue but looks like it could be:

**To Reproduce**
Steps to reproduce the behavior:
1. Log in
2. Add something to cart
3. Go to checkout, you should be able to proceed it as Logged In user (you can see that shipping and billing sections display address picker with your addresses)
5. Refresh the page (press `f5`)
6. Checkout does not recognize yours Logged In state

**Comment by mateuszwozniak** [comment]
@tutok, you're right. It looks like it's related to the same issue.
