### ISSUE TITLE
Extending extension strategies

### ISSUE THREAD

**Issue by leon0v** [deity-io/falcon#430]
Hi :)

I want to add my custom Magento 2 product attribute to the [falcon-shop-extension](https://github.com/deity-io/falcon/tree/dev/packages/falcon-shop-extension). I only need to add the field to the Product type in the schema.graphql, and i need to change the `reduceProduct()` function in [falcon-magento2-api](https://github.com/deity-io/falcon/tree/dev/packages/falcon-magento2-api) so it adds my attribute to the returned response.

What is the best way of doing this? Should i make a custom extension which in some way imports [falcon-shop-extension](https://github.com/deity-io/falcon/tree/dev/packages/falcon-shop-extension), alters it, and then exports it again? Or are there easier ways?

Greetings

**Comment by leon0v** [comment]
I tried making my own extension, then import the schema.graphql from falcon-shop-extension, and add
 
`extend type Product {
  pdf: String
}`

to the typeDefs but because of how [getRootTypeFields() in falcon-server-env removes the "extend type X"](https://github.com/deity-io/falcon/blob/dev/packages/falcon-server-env/src/models/Extension.ts#L163) from the typeDefs, the `makeExecutableSchema()` function gives an error because now there are 2 types named Product.

**Comment by Borales** [comment]
Hi @leon0v 

Removing `extend type X` was made to remove any external dependencies for other types, but we haven't foreseen multiple partial type definitions within a single GQL file. In this particular case - it would be better to create a separate extension and extend Shop types in it. 
I'll try to think about how we could improve this part.

**Comment by cane-lagerwaard** [comment]
Hi @leon0v in the meantime you could also take a look at this PR for our documentation https://github.com/deity-io/falcon-docs/pull/55 to learn more about this topic

**Comment by leon0v** [comment]
@Borales @cane-lagerwaard 

Thanks! Updated docs are very helpful :)
