### ISSUE TITLE
RFC: Re-work of falcon-ecommerce-uikit library

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon#436]
The purpose of this issue is to plan rework of the `@deity/falcon-ecommerce-uikit` package. The initial idea was to have a set of UI components that help building UI for shops. Unfortunately over the time we put almost everything related to front-end of shop in there - Queries, Mutations, higher order components that provide logic without rendering UI, reusable UI pieces and even full page views.

Because of that it's very hard to maintain that library and also provide enough flexibility so developers are not forced to use particular things.

Besides architectural issues there are a lot of issues with naming (mentioned at the end of this description) that we need to solve during this word.

> NOTE: the term "business level components" in this issue relates to the components that do not render UI by themselves but provide a piece of logic that's required to achieve a particular functionality. That mostly covers Higher Order Components and Render Prop Components.

The list with everything that's inside `@deity/falcon-ecommerce-uikit` is [here](https://github.com/deity-io/falcon/blob/uikit-rework/packages/falcon-ecommerce-uikit/uikit.md). Before adding comments here please get familiar with that list as it's an entrypoint to the discussion about potential changes. Once you go through that list you'll understand why we have to the changes listed below :)

# 1. Goals to achieve:

1. Organizing the code into separate logical packages (UI, business logic, data access)
2. Splitting the code to small units (component per file approach?) so component overriding works at all levels
3. Providing documentation for everything (listing components and their purpose)
4. Moving pieces that should not be inside separate libraries to the example shop
5. Unifying naming convention
6. Produce conventions/standards for naming:

- gql constants
- Query and Mutation components
- data types
- "business level" components
- UI components

## NOTES

- `RenderProps` vs `InjectedProps` (e.g. `EnsureTTIRenderProps` and `CheckoutLogicInjectedProps`)
- `Logic` vs `Provider` (e.g. `CheckoutLogic` and `FiltersDataProvider`)
- `SomethingLayout` components (created usually with `themed()` call or as React.SFC) vs `itemSomethingLayout` properties - defined as props of `DefaultThemeProps` type - both have "Layout" in the name and that's confusing. Examples: `MiniFormLayout` (React.SFC), `AddressCardLayout` (`themed()`) and `orderItemSummaryLayout` (const of `DefaultThemeProps` type)
- inconsistencies between query names and its data (`OrderListQuery` returns `OrdersData`, while it should be `OrderListData`)

# 2. Suggested changes

## 2.1. Suggested packages

- `falcon-uikit` (contains all high level UI components for both blog and shop as well as "business level components")
- `falcon-shop-data` (contains gql definitions, Queries and Mutations for shop)
- `falcon-blog-data` (contains gql definitions, Queries for blog)
- `falcon-data` (contains base classes for Queries, Mutations and front-end data layer)
- `falcon-front-kit` (contains front-end business logic component)
- move TypeScript typings to packages with related GraphQL schema files (see below)

## 2.2. TypeScript types

Currently we have TS types scattered across whole repository - usually when some component needs to use a particular type it defines it in the folder that the component itself is placed in. What's worse we have multiple definitions of the same types in a few places and types that are "similar" to GraphQL types but with small differences.

We should aim to make types consistent across all the packages and modules (types in GraphQL schema, types in UI modules that use TS, types in GraphQL resolvers). So in that case TS types should be placed probably in `@deity/falcon-shop-extension`. That way we can import them in API classes as well as in UI components (as dev dependency).

## 2.3. Suggested naming changes and conventions

1. "`Layout`" related changes

As mentioned above there are 3 types of layout definitions we have. In many cases these are used interchangeably for React component name and default theme props name. Next, these props are mixed and because of that in some places it's clear which property defines theming key, in other places it's not entirely clear. Let's consider the following examples:

```typescript
// below we have "Layout" in the name while it's not the layout, it's component's theme - we have this pattern in multiple files
const miniFormLayout: DefaultThemeProps = {
  miniFormLayout: {
    // <-- matches component name, so it's easy to change theme of MiniFormLayout
    display: 'grid',
    gridRowGap: 'md'
  }
};

// "Layout" below is the real Layout component - it's a layout for MiniForm
export const MiniFormLayout: React.SFC<{ title?: string }> = ({ title, children }) => (
  <Box defaultTheme={miniFormLayout}>
    {title && <H3>{title}</H3>}
    <FixCenteredLayout maxWidth="70%">{children}</FixCenteredLayout>
  </Box>
);
```

So it would be better to change:

```typescript
const miniFormLayout: DefaultThemeProps = {
```

to

```typescript
const miniFormTheme: DefaultThemeProps = {
```

That way we get consistent naming, and it's easy to find out what theme key should be changed to style particular component.

Another case is inconsistency in the `defaultTheme` property (which is a variation of above case):

```typescript
export const AddressCardLayout = themed({
  // <-- Layout used as component name
  tag: 'li',
  defaultTheme: {
    addressCard: {
      // <-- no 'layout' here, so it should be renamed to "addressCardLayout" to keep things consistent
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start'
    }
  }
});
```

So to keep things consistent we should adapt the following patterns:

```typescript
export const MyCustomComponent = themed({
  tag: 'li',
  defaultTheme: {
    myCustomComponent: {
      // theme definition
    }
  }
});
```

and

```typescript
const myCustomComponentTheme: DefaultThemeProps = {
  myCustomComponent: {
    // theme definition
  }
};

export const MyCustomComponent: React.SFC<{}> = props => (
  <Box defaultTheme={myCustomComponentTheme}>{/* component content */}</Box>
);
```

2. `RenderProps` instead of `InjectedProps`, so rename the following:

- `CheckoutLogicInjectedProps` -> `CheckoutLogicRenderProps`
- `ProductConfiguratorInjectedProps` -> `ProductConfiguratorRenderProps`
- `TwoStepWizardInjectedProps` -> `TwoStepWizardRenderProps`

3. **[todo]** Unified way of naming HOC and "render props" components, as right now we have components with suffixes like `Logic` and `Provider` and also plain names like `Form`, `Field` etc. We could probably remove suffixes but the problem is that changing `CheckoutLogic` to `Checkout` might cause name collision with UI widgets.

## 2.4. Suggested naming convention for react-apollo components and related types

1. Query components should end with `Query` (`CountriesQuery`, `CategoryProductsQuery`, etc)
2. Mutation components should end with `Mutation` (`EditAddressMutation`, `AddAddressMutation`, etc)
3. GraphQL constants (strings) for queries should start with `GET_` (`GET_ADDRESS`, `GET_PRODUCT`)
4. GraphQL constants (strings) for mutations should have `DO_SOMETHING` format (`SET_ADDRESS`, `APPLY_COUPON`)
5. TypeScript types for query and mutation results should have name created by removing `Query`/`Mutation` from component name (`ProductQuery` -> `Product`, `AddressListQuery` -> `AddressList`)
6. Input types should have name created by replacing `Query`/`Mutation` with `Input` (`SignInMutation` -> `SignInInput`, `AddAddressMutation` -> `AddAddressInput`)

## 2.5 GraphQL schema changes

As a part of the rework of uikit we should probably also fix some issues in our schema files, so TS typings can be properly added:

- some `input` types don't have `Input` in the name (`SignUp`, `SignIn`, `ShopPageQuery`, `CustomerPassword`, `CustomerPasswordReset`) - these should be renamed (so we can add correct TS typings for those)

- `ID` type should be used for all ids (it handles both string and number values, so we can be platform agnostic, because atm we added ids based on Magento types)

**Comment by tutok** [comment]
we could lint graphql queries via https://github.com/apollographql/eslint-plugin-graphql

**Comment by nimobeeren** [comment]
Some comments on the GraphQL schema changes. I agree with the proposed changes but I would like to address some other issues.

### Duplication and inconsistencies
There are some types that are very similar, but are defined independently. This leads to small inconsistencies and duplication, making maintanance more difficult. As an example, take the types related to addresses. We have `Address`, `AddressInput`, `EditAddressInput` and `AddAddressInput`. Each of these has a collection of scalar subfields. Rather, we should have a generic `Address` type, which these other types is composed of. Take this proposed type:
```
type AddressInput {
  id: ID!
  terms: ID
  customerId: ID
  customerAddressId: ID
  sameAsBilling: Boolean
  defaultBilling: Boolean
  defaultShipping: Boolean
  address: Address!
}
```
We reuse the already defined `Address` type, and add any fields specific to this type (on another note, we should check whether all these fields are useful).

### Specific issues
- `breadcrumbs(path: String!)`. In the case of BigCommerce, we do not use the `path` parameter. The parameter should not be required.
- `Customer.websiteId: Int`. I could not find a purpose of this field that cannot be solved by just using the `id` field. So I see no reason to have it in the schema. Similarly, `CustomerInput.websiteId: Int!`. Here the field could be changed to `id: ID!`
- `type Country`. In the case of BigCommerce, countries also have a numerical ID, which could be represented as a field `id: ID`. The `code: String!` field should not be required, to maximize compatibility with various backends.
- `EditAddressInput`. Has too many required fields. Only `id` should be required, to allow updating any number of fields.
- Many fields regarding pricing are not clearly defined. For example, `CartItem`, `OrderItem` and `Order` have fields like `priceInclTax`, `rowTotalInclTax`, `rowTotalWithDiscount`, `baseGrandTotal` and `discountAmount`. It is often not clear whether the prices include tax, discounts or both. We should think about
