### ISSUE TITLE
The first item added to minicart has price zero

### ISSUE THREAD

**Issue by leonvisscher** [deity-io/falcon#443]
**Describe the bug**
When you add an item to an empty minicart, the price is set at 0. If you update the item, or add an item to the cart when there is already an item in it, there is no problem.

**To Reproduce**
1. Add item to empty minicart
2. See that price is 0

**Expected behavior**
Correct price is shown

**Screenshots**
![Screenshot from 2019-05-15 10-13-12](https://user-images.githubusercontent.com/17271164/57759395-29669100-76fa-11e9-926c-f1dfb198d173.png)
![Screenshot from 2019-05-15 10-13-39](https://user-images.githubusercontent.com/17271164/57759396-29669100-76fa-11e9-9068-b7cfee78b64f.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- Browser: chrome
- Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by leon0v** [comment]
When I add an item through Postman, you can see the REST API doesn't return the price if you add an item to an empty cart:

Add item to empty cart, price not returned:
![Screenshot from 2019-05-15 10-32-29](https://user-images.githubusercontent.com/17271164/57761122-2325e400-76fd-11e9-9532-5117d5a87db2.png)

Add another item, price returned:
![Screenshot from 2019-05-15 10-33-31](https://user-images.githubusercontent.com/17271164/57761125-24efa780-76fd-11e9-8955-9d1e089bef05.png)

**Comment by Borales** [comment]
@leon0v hi

we had a bug report for this issue in Magento repository (https://github.com/deity-io/falcon-magento2-development/issues/83), looks like it needs to be revalidated.

**Comment by Borales** [comment]
hi @leon0v 
I just noticed that you're using your local Magento instance. Could you please check the version of falcon-magento (PHP) module you're using? (https://github.com/deity-io/falcon-magento2-module/blob/master/CHANGELOG.md)

**Comment by leon0v** [comment]
Hi @Borales ,

I am using version 4.0.2, but i can also reprocue on http://demo.deity.io . The first time you add an item to an unused cart, the price shows correctly, but when you delete all items and then add an item to the empty cart the price is zero.

**Comment by Borales** [comment]
@leon0v yep, we managed to reproduce it. I will pass this info to @sergy-gzh
