### ISSUE TITLE
Minicart item amount not updated after add product multiple times

### ISSUE THREAD

**Issue by leonvisscher** [deity-io/falcon#445]
**Describe the bug**
When you add the same product multiple times, the number in Minicart is not updated. 

**To Reproduce**
1. Go to random product
2. Configure options and click on Add To Cart
3. Close the sidebar, choose the same product options and add again.
4. Minicart still says there is 1 of that product in it
5. If you click on Secure Checkout, there are in fact 2 of the product in the cart

If you alter the number input in minicart again, this will override the actual number of items in cart.

**Expected behavior**
Number input field in minicart shows correct values

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- Browser: chrome
- Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by cane-lagerwaard** [comment]
Fixed by https://github.com/deity-io/falcon/pull/518 

Closing this issue
