### ISSUE TITLE
Account icon in header doesn't update after log out

### ISSUE THREAD

**Issue by leonvisscher** [deity-io/falcon#446]
**Describe the bug**
After you log out on the /account page, the AccountIcon in the Header is still a Link to /account. The CustomerQuery does get refetched after the SignOutMutation (which it should do), but the CustomerQuery in the Searchbar component does not re-render its contents, which it should because the Query got refetched.

[Here](https://github.com/deity-io/falcon/blob/dev/packages/falcon-ecommerce-uikit/src/Header/Header.tsx#L47) there is still a <Link> comp displayed, but { customer } is now null.

**To Reproduce**
1. Go to https://demo.deity.io/
2. Sign in and click on account icon
3. Click Log out
4. Click on account icon again.
5. You get send to /account,

**Expected behavior**
The Sidebar should open with SignIn content displayed.

**Additional context**
I think this issue is related to [this issue](https://github.com/apollographql/apollo-client/issues/3633).

**Comment by Borales** [comment]
@leonvisscher Hi. Could you please specify your tested browser? Thanks.

(I tested it in Chrome - it works as expected)

**Comment by Borales** [comment]
https://github.com/deity-io/falcon/pull/521#issuecomment-512139558

**Comment by akbarik** [comment]
@Borales, I also tested it in Chrome on Mac OS. I was in `dev` branch, is that the same for you?
