### ISSUE TITLE
Magento 2 Integration - Product Page not working

### ISSUE THREAD

**Issue by bellodaniel** [deity-io/falcon#466]
**Describe the bug**
I have just integrated Deity Falcon on my local Magento 2 environment.
Products are shown on the category page: https://cl.ly/6e3190ccfc51
However, when I go to a product page, I get an error: https://cl.ly/4f2568acf511
```
Error!: NOT_FOUND
Error: GraphQL error: Request does not match any route.
```
Is there anything I am missing?
**To Reproduce**
1. Connect Magento 2 with Deity Falcon.
2. https://falcon.deity.io/docs/backend/installing-magento2
3.https://falcon.deity.io/docs/getting-started/installation
4. Go to Product Page.

**Expected behavior**
I should see the PDP so that I am able to test the checkout operation.

**Screenshots**
https://cl.ly/4f2568acf511

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [All browsers]
**Additional context**

**Comment by cane-lagerwaard** [comment]
Hi @bellodaniel are you still encountering this issue?

**Comment by bellodaniel** [comment]
Hello @cane-lagerwaard 
It should have been an issue with my local environment. I tried on another machine and it works well.
Thanks.
