### ISSUE TITLE
Bug retrieving custom attributes for one product

### ISSUE THREAD

**Issue by leonvisscher** [deity-io/falcon#472]
**Describe the bug**
In the [product resolver](https://github.com/deity-io/falcon/blob/dev/packages/falcon-magento2-api/src/index.js#L744) the `async fetchProduct(id)` is called. In `async fetchProduct(id)` the `this.convertAttributesSet(data);` & `this.convertKeys(data);` are called. Afterwards in the product resolver, the [`reduceProduct(data)`](https://github.com/deity-io/falcon/blob/dev/packages/falcon-magento2-api/src/index.js#L747) is called, where `this.convertAttributesSet(data);` & `this.convertKeys(data);` are called again. Because of this, the custom attributes get stripped off.

Custom attributes do return when fetching category because the convertKeys method is only called once.

**To Reproduce**
1. Query product
2. No custom attributes

**Expected behavior**
Custom attributes are shows

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- Browser: chrome
- Version Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
"@deity/falcon-magento2-api@^0.6.0",

**Comment by leon0v** [comment]
Solution:

Don't call `this.convertAttributesSet(data);` & `this.convertKeys(data);` in the `async fetchProduct(id)` function.

**Comment by mateuszwozniak** [comment]
Thanks for the report, we didn't notice that indeed. We're going to cleanup all the data conversion a bit as part of #435 so this one will also be fixed with that.
