### ISSUE TITLE
Edit customer endpoint not defined

### ISSUE THREAD

**Issue by leon0v** [deity-io/falcon#473]
**Describe the bug**
The [`editCustomer`](https://github.com/deity-io/falcon/blob/dev/packages/falcon-magento2-api/src/index.js#L1328) resolver for the EditCustomer Mutation requests the `/falcon/customers/me/` endpoint. This endpoint does not exist in [falcon-magento2-module](https://github.com/deity-io/falcon-magento2-module/tree/master/src/Deity)

**Expected behavior**
Update customer information

**Screenshots**
![image](https://user-images.githubusercontent.com/17271164/58881987-9a86dc00-86db-11e9-93ba-c432a0e76d85.png)

**Comment by Borales** [comment]
Hi @leon0v 
Good point! you're right.

It's going to be fixed today 👍 thanks for the report.

**Comment by leon0v** [comment]
Great :), also there is no confirmation or error message after the Mutation is finished
