### ISSUE TITLE
Minicart quantity is not updated after adding product multiple times 

### ISSUE THREAD

**Issue by Vanessa1906** [deity-io/falcon#502]
**Describe the bug**
When you add the same product multiple times, the number in Minicart is not updated.

**To Reproduce**

- Go to random product
- Configure options and click on Add To Cart
- Close the sidebar, choose the same product options and add again.
- Minicart still says there is 1 of that product in it

**The video for reproduce** 
https://www.loom.com/share/a0a9e60f59544334be24533a601f2067

Expected behavior
Number input field in minicart shows correct values

Desktop (please complete the following information):

OS: Ubuntu 18.04.1 LTS
Browser: chrome
Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by Piralein** [comment]
duplicate [#445](https://github.com/deity-io/falcon/issues/445)

**Comment by hoang08021996** [comment]
Hi . Do you have any idea for fixing ?

**Comment by thanhnd0905** [comment]
Hello everyone . I got the same issue . How to fix it ?

**Comment by cane-lagerwaard** [comment]
Looks like there's a missing `refetchQueries` entry which fetches the new data
