### ISSUE TITLE
add d.ts watch into falcon-scripts

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#514]
**Is your feature request related to a problem? Please describe.**
falcon-scripts have already `watch` but it does not generate typings

**Describe the solution you'd like**
https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher

**Comment by sergy-gzh** [comment]
A bit more to it.
falcon-scripts does not generate `cjs`.

**Comment by tutok** [comment]
d.ts watch is implemented, so closing it.
