### ISSUE TITLE
Pricing not consistent for discounted products between pages

### ISSUE THREAD

**Issue by EddyVinck** [deity-io/falcon#523]
**Describe the bug**
The price of products is different in the productlist compared to the product page.

**To Reproduce**
1. Go to the men's product list https://demo.deity.io/men.html
2. Scroll to a discounted product like https://demo.deity.io/zeppelin-yoga-pant.html and notice the price
3. Click on the product
4. Compare the `special` price

**Expected behavior**
The pricing should be consistent between pages.

**Screenshots**
The product list:
![gql-request-men](https://user-images.githubusercontent.com/23434753/61225119-3a467980-a720-11e9-9c29-55ff50f0a1ca.PNG)

The product page:
![gql-request-men-product-page](https://user-images.githubusercontent.com/23434753/61225122-3e729700-a720-11e9-872c-86b145a199e7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version  75.0.3770.100

**Additional context**
This is both in the demo application as projects created with `yarn create falcon-app my-app`. I looked at the code, but I am not sure where the error comes from and I didn't have more time to look into it further today.

**Comment by nimobeeren** [comment]
I did some testing and it appears the response coming from the Magento REST API is also incorrect. These are the requests/responses being made for the category page and product page, respectively:

**`GET https://magento.deity.io/rest/default/V1/falcon/products/MP08`**

    {
      "filters": ...
      "items": [
        ...
        {
          "id": 834,
          "type_id": "configurable",
          "price": {
            "regular_price": 82,
            "special_price": 49.2,
            "min_tier_price": null
          },
          "is_salable": 1,
          "sku": "MP08",
          "name": "Zeppelin Yoga Pant",
          "image": "https:\/\/magento.deity.io\/media\/catalog\/product\/cache\/e1e1b07e8958d0ff99cb20927d7766af\/m\/p\/mp08-green_main_1.jpg",
          "url_path": "zeppelin-yoga-pant.html",
          "custom_attributes": [
            {
              "attribute_code": "category_ids",
              "value": [
                "18",
                "32",
                "8",
                "2"
              ]
            }
          ]
        },
        ...
      ]
    }

**`GET https://magento.deity.io/rest/default/V1/falcon/products/MP08`**

    {
      "id": 834,
      "description": "<p>Climb every mountain, or hold every pose, in the all-purpose Zepellin Yoga Pant. With its thin fleece interior and smooth layer-friendly surface, you'll get all the comfort and versatility you need.<\/p>\n<p>&bull; Smooth exterior for easy over-layering.<br \/>&bull; Brushed fleece interior insulates and wicks. <br \/>&bull; No-roll elastic waistband with inner drawstring.<br \/>&bull; Chafe-resistant flatlock seams.<\/p>",
      "price": {
        "regular_price": 82,
        "special_price": 65.6,
        "min_tier_price": null
      },
      "sku": "MP08",
      "name": "Zeppelin Yoga Pant",
      ...
    }

As you see, the `special_price` is inconsistent.

I'm not sure how to fix this.

**Comment by EddyVinck** [comment]
Nice find! I'm not sure either.

**Comment by sergy-gzh** [comment]
Was the issue with price index + catalog rule on magento side.
