### ISSUE TITLE
Jest breaks on files that haven't been transpiled yet

### ISSUE THREAD

**Issue by EddyVinck** [deity-io/falcon#525]
**Describe the bug**
I tried to write some tests, but was not able to do so with how Falcon is configured out of the box. This occurred when I wanted to test a component that relies on `ApolloProvider`, as provided by `FalconClientMock`.

**To Reproduce**
1. setup sample project: `$ yarn create falcon-app my-app`
2. install dependencies: `$ cd client && yarn`
3. Copy this test from [the docs](https://falcon.deity.io/docs/falcon-client/basics#mocking-falcon-client):
```js
// Sample.test.js
import { FalconClientMock } from '@deity/falcon-client/test-utils';

describe('<Component />', () => {
  test('renders without exploding', () => {
    ReactDOM.render(
      <FalconClientMock>
        {
          // your <Component />
        }
      </FalconClientMock>,
      document.createElement('div')
    );
  });
});
```
4. `$ yarn test`
5. See error in console:
```
 PASS  src/App.test.js
 FAIL  src/components/Sample.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/eddy/dev/sample-falcon-app/my-app/client/node_modules/@deity/falcon-client/test-utils/index.js:2
    export { default as FalconClientMock } from './FalconClient';
    ^^^^^^

    SyntaxError: Unexpected token export

    > 1 | import { FalconClientMock } from "@deity/falcon-client/test-utils";
        | ^
      2 | 
      3 | describe("<Component />", () => {
      4 |   test("renders without exploding", () => {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (src/components/Sample.test.js:1:1)
```

**Expected behavior**
Jest should be configured so modules get transpiled when they are imported.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 and Windows 10
 - Node v12.6.0

**Additional context**
This is an issue for any package that has not been transpiled yet, not just packages from `@deity`

**Comment by EddyVinck** [comment]
I just took a quick look at this again, and it seems like Falcon Client does not support `babel.config.js`, which is why my config may have not worked. See: https://github.com/deity-io/falcon/blob/dev/packages/falcon-client/build-utils/paths.js#L60

I can  try creating `.babelrc` as opposed to `babel.config.js` sometime soon, but it would be nice if there was support for `babel.config.js` because it is recommended by Babel and it offers more flexibility for developers. See: https://babeljs.io/docs/en/configuration

This isn't a fix for this issue, however I feel like it is worth mentioning.

**Comment by EddyVinck** [comment]
I just tested this (with node 11) and it still breaks the same way as I described above using `$ yarn create falcon-app my-app`

_However_, in the Falcon project itself (dev branch):

```zsh
cd falcon/examples/shop-with-blog
cd client
yarn
```
Then, adding the following to `falcon/examples/shop-with-blog/client/src/App.test.js`:
```js
// App.test.js
import React from 'react';
import ReactDOM from 'react-dom';
import { FalconClientMock } from '@deity/falcon-client/test-utils';

describe('<Component />', () => {
  test('renders without exploding', () => {
    ReactDOM.render(
      <FalconClientMock>
        <div />
      </FalconClientMock>,
      document.createElement('div')
    );
  });
});
```
Run the tests in the `client` folder: `yarn test`
```zsh
 PASS  src/App.test.js
  <Component />
    ✓ The tests run (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.652s, estimated 1s
```
I'm not sure what's causing the tests to fail in a `yarn create falcon-app` project, but for some reason they work within the example project in the Falcon repo. Maybe `create-falcon-app` needs to be updated to reflect the example project's setup?

**Comment by tutok** [comment]
> Maybe create-falcon-app needs to be updated to reflect the example project's setup?

exactly 😛

**Comment by EddyVinck** [comment]
I just went through your PR and was able to fix the issue by copying your code to my local version of `@deity/falcon-client`. I also needed to add the `__fakes__` folder, as that did not exist yet within my version of `@deity/falcon-client`.

Happy this will be fixed soon! :tada: Nice work @tutok :+1:
