### ISSUE TITLE
"Category id = 25" error 

### ISSUE THREAD

**Issue by marcelowu** [deity-io/falcon#544]
![2019-08-04 12-39-46屏幕截图](https://user-images.githubusercontent.com/30912144/62425989-df1bfd00-b6b5-11e9-8fcb-6f790f5a4380.png)
![2019-08-04 12-41-30屏幕截图](https://user-images.githubusercontent.com/30912144/62425990-dfb49380-b6b5-11e9-9d6d-e1628d494a6a.png)

**Comment by cane-lagerwaard** [comment]
Hi @marcelowu this is a known thing: you can check our troubleshooting section in the documentation which should solve it https://falcon.deity.io/docs/support/troubleshooting#error-no-category-found-with-id-25

**Comment by wubuyun** [comment]
ERROR in ./src/pages/shop/Checkout/components/PaymentMethodItem.js
Module not found: Error: Can't resolve '@deity/falcon-adyen-plugin'

npm install --save @deity/falcon-adyen-plugin
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/Adyen/adyen-cse-web.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Borales** [comment]
@wubuyun looks like you don't have `git` installed on your system.

**Comment by wubuyun** [comment]
Thanks..

**Comment by wubuyun** [comment]
deity-falcon is ok...
error acess admin magento2.3.2 

![2019-08-09 23-01-21屏幕截图](https://user-images.githubusercontent.com/35350235/62816189-cf5b4900-baf9-11e9-83a6-3dcf56e1cf31.png)
![2019-08-09 23-00-27屏幕截图](https://user-images.githubusercontent.com/35350235/62816191-d5512a00-baf9-11e9-8e00-05a001ad6643.png)
