### ISSUE TITLE
error sandbox paypal

### ISSUE THREAD

**Issue by wubuyun** [deity-io/falcon#556]
![2019-08-18 02-06-23屏幕截图](https://user-images.githubusercontent.com/35350235/63220400-116d3600-c15d-11e9-9d36-3ee99d4613f2.png)

**Comment by cane-lagerwaard** [comment]
Hi @wubuyun could you please use the bug report template and/or give us some more information?

**Comment by marcelowu** [comment]
![2019-08-20 23-37-54屏幕截图](https://user-images.githubusercontent.com/30912144/63398382-c09b4e80-c3a3-11e9-9842-45c1599851ef.png)
