### ISSUE TITLE
No "cancel order"

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#586]
**Is your feature request related to a problem? Please describe.**
As a user I can not cancel a placed order in the UI.

**Describe the solution you'd like**
A cancel button to cancel the order as customer.

**Describe alternatives you've considered**
Some way to cancel an order.

**Additional context**

**Comment by cane-lagerwaard** [comment]
Hi @DanielRuf, we'll integrate this feature in the upcoming redesign of the demo shop. Thanks!
