### ISSUE TITLE
Confusing resolutions entry in example

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#597]
**What should be changed/improved?**
The current `resolutions` field int he example sets the `apollo-env` to `0.3.1` but package.json says / wants `0.4.0`.

**Your suggested solution**
Should the resolutions filed be removed or updated to `"apollo-env": "0.3.1"`?

https://github.com/deity-io/falcon/blob/master/examples/shop-with-blog/server/package.json#L32

**Comment by cane-lagerwaard** [comment]
@Borales any ideas?

**Comment by Borales** [comment]
@DanielRuf hi. Yes, you're right, those resolutions must be updated as well.

**Comment by Borales** [comment]
@DanielRuf it will be fixes with https://github.com/deity-io/falcon/pull/596
