### ISSUE TITLE
ServiceWorker - CONFIG values during development

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#599]
After running `yarn start` - the generated `examples/shop-with-blog/client/build/sw.js` file does not contain the condition for `if` statement:

- template ([source](https://github.com/deity-io/falcon/blob/dev/packages/falcon-client/src/serviceWorker/sw.js#L91)):
```
if (!CONFIG.precache) {
  return fetch(url.href);
}
```
- generated:
```
{
  return fetch(url.href);
}
```

`build:dev` and `build:prod` commands generate this file correctly.

**Comment by tutok** [comment]
I would not consider it as an error at all.
please look into configuration which is:

```
 serviceWorker: {
    precache: process.env.NODE_ENV === 'production',
    blacklistRoutes: config.proxyEndpoints || []
  },
```
so `serviceWorker.precache` on dev server mode is `false`, 
so `if (!CONFIG.precache)` is always true (because `!false` is always `true`).
so that is why rollup terser removes `if` statement
