### ISSUE TITLE
Configurable / better chunk settings

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#603]
**What should be changed/improved?**
Currently there is one big chunk per entry / part like client.js.

**Your suggested solution**
https://webpack.js.org/plugins/split-chunks-plugin/
Leverage / use the chunk settings to improve the performance (just an example):
```
		chunks: 'async',
        minSize: 800,
        maxSize: 1600,
        minChunks: 1,
        maxAsyncRequests: 5,
        maxInitialRequests: 3,
        automaticNameDelimiter: '~',
        automaticNameMaxLength: 30,
        name: true,
```

**Comment by tutok** [comment]
https://github.com/deity-io/falcon/issues/155
