### ISSUE TITLE
Can not use boopathi/react-svg-loader

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#604]
**Describe the bug**
When I try to use https://github.com/boopathi/react-svg-loader I get errors due to the loader (in the import).

`Error: Non-whitespace before first tag` whcih points to some `m`, probably `module`.

**To Reproduce**
1. Eject the Deity PWA
1. Install https://github.com/boopathi/react-svg-loader
2. Load a svg using the import statement with the `react-svg-loader!`
3. Run `yarn start` or `yarn build:prod`

**Expected behavior**
The loader should work.

**Screenshots**

**Additional context**

**Comment by Borales** [comment]
@DanielRuf thank you for this report. In order to help with this issue - could you please expand the "reproduce" section with more detailed steps? (e.g. installing the plugin/loader, changing the build config, using svg file etc)

**Comment by DanielRuf** [comment]
Generally there is not much more, the loader is used through the import statement and loads the SVG file.

The steps are already included. The build config (there is no real one, at least no webpack config file or babelrc) was not touched.

**Comment by Borales** [comment]
@DanielRuf I'd suggest using it in conjunction with babel loader.

**Comment by mateuszwozniak** [comment]
@DanielRuf how do you import the image? With the inline loader? If so then use `!!` in front of the loader to disable pre and post loaders and that should work. I've just tested this inside `src/pages/Home.js`:
```
import SvgImage from '!!react-svg-loader!src/assets/image.svg'; // notice !! before loader name
```
then in the code below simply:
```
<SvgImage width={100} height={100} />
```
and it works correctly.

If you don't want to use inline loaders you can inject webpack config for the loader, see the details [here](https://falcon.deity.io/docs/falcon-client/configurations#webpack)

**Comment by DanielRuf** [comment]
Thanks for the hintm, this seems to work.

Interestingly all docs refer to `-!`. Where did you find this information?

**Comment by mateuszwozniak** [comment]
Actually `-!` also should work because it will disable preloaders but just for being sure I disabled everything. 

All these options are mentioned [here](https://webpack.js.org/concepts/loaders/#inline).

**Comment by DanielRuf** [comment]
> Actually `-!` also should work because it will disable preloaders but just for being sure I disabled everything.

Unfortunately this approach did not work so it seems there are more loaders as the error also suggested.

At least one solution even if the client bundle gets bigger due to this (which is not ideal).

**Comment by DanielRuf** [comment]
> Actually `-!` also should work because it will disable preloaders but just for being sure I disabled everything.

Unfortunately this approach did not work so it seems there are more loaders as the error also suggested.

At least one solution even if the client bundle gets bigger due to this (which is not ideal).

In this case it is some postLoader as it seems.
