### ISSUE TITLE
basic auth not supported

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#615]
**Describe the bug**
When the M2 instance is protected by basic auth, it does not work. Even if we set `username` and `password` in the config as these are not used at all.

The client shows the following:
```shell
[2019-09-30 14:29:12.445] ERROR: Internal Server Error! Request: /
[2019-09-30 14:29:12.445] ERROR: GraphQL error: undefined

File: /home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/src/errors/ApolloError.ts
-
-

    Error: GraphQL error: undefined
        at new ApolloError (/home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/src/errors/ApolloError.ts:56:5)
        at QueryManager.<anonymous> (/home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/src/core/QueryManager.ts:590:31)
        at step (/home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/node_modules/tslib/tslib.es6.js:99:1)
        at Object.next (/home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/node_modules/tslib/tslib.es6.js:80:45)
        at /home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/node_modules/tslib/tslib.es6.js:73:1
        at new Promise (<anonymous>)
        at __awaiter (/home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/node_modules/tslib/tslib.es6.js:69:1)
        at /home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/src/core/QueryManager.ts:524:31
        at /home/druf/Schreibtisch/projects/deity-test/pwa/client/build/webpack:/src/core/QueryManager.ts:1201:11
        at Array.forEach (<anonymous>)
[2019-09-30 14:29:33.256] ERROR:
    locations: [
      {
        "line": 2,
        "column": 3
      }
    ]
    path: [
      "backendConfig"
    ]
    extensions: {
      "code": "UNAUTHENTICATED"
    }

```

**To Reproduce**
1. Setup M2 and protect it with basic auth
1. Install the M2 module
2. Try to use the OAuth implementation

**Expected behavior**
basic auth should work

**Comment by Borales** [comment]
@DanielRuf setting `username` and `password` in the config (if we're talking about the app config) is not enough, it has to be supported by the code of the package (in this case - `falcon-magento2-api`). Such basic auth is not supported in this package, since it may mess up with the real auth on the Magento side.

**Comment by DanielRuf** [comment]
Right. So this feature request will not be implemented?

**Comment by Borales** [comment]
@DanielRuf not right away (as we have tasks with a higher priority right now). We will probably take care of it eventually, but only when important things are done.

Besides, we would be more than happy to accept a PR with this feature.

**Comment by Borales** [comment]
@DanielRuf btw, have you tried https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding? (not sure if fetcher supports such definition tho)

**Comment by DanielRuf** [comment]
> @DanielRuf btw, have you tried https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding? (not sure if fetcher supports such definition tho)

No, this does not work as the URL is formatted from the object that we provide in the config file.

**Comment by Borales** [comment]
@DanielRuf `"host": "user:password@magento.example.com"` - I meant this way

**Comment by DanielRuf** [comment]
No, then the GraphQL server says that this is not a valid URL. This is not a valid host.

See
https://nodejs.org/api/url.html#url_url_host
https://nodejs.org/api/url.html#url_url_password
https://nodejs.org/api/url.html#url_url_username

**Comment by DanielRuf** [comment]
At least in this case. I think you have your own `url.format` which does not include the mentioned properties.

**Comment by Borales** [comment]
oh right, it's [here](https://github.com/deity-io/falcon/blob/3b11db9c36932c63e78c2bb82638b5e596de1c6c/packages/falcon-server-env/src/helpers/url.ts). Yeah, it needs to be implemented, sorry.

**Comment by DanielRuf** [comment]
Right and hostname !== host =)

https://github.com/deity-io/falcon/blob/3b11db9c36932c63e78c2bb82638b5e596de1c6c/packages/falcon-server-env/src/helpers/url.ts#L18

Otherwise it would probably work. Why not use `Object.assign()` to pass everything through as is?
Or merge these? There might be more which might the needed probably.

**Comment by sergy-gzh** [comment]
An update for this issue.
There is a collision with Basic Auth and Oauth together.
The reason is they both are using `Authorization` header for access token transfer.
Only format differs.
For Basic auth:
`Authorization: Bearer 6cqypmv19o095j8gtoqr842xo9pcz0vo`
For Oauth1.0 that will be like
`Authorization: OAuth oauth_consumer_key="7665kt...`
So its not possible to have both of those systems in one request.
As a workaround consider IP whitelisting or putting services in the same network (virtual network) instead.
P.S.
There seems to be the way to pass Oauth credentials with uRL/request body, but magento does not support that atm.
