### ISSUE TITLE
Strange breadcrumb/link behaviour

### ISSUE THREAD

**Issue by jahvi** [deity-io/falcon#62]
**Describe the bug**
Some links are getting malformed under certain conditions which causes a blank page to show.

**To Reproduce**

1. On the sample shop, go to "Women" category
2. Click on "Tiffany Fitness Tee"
3. Click on "Tees" in breadcrumbs
4. Click on "Tiffany Fitness Tee"
5. Click on "Tops" in breadcrumbs (or any other breadcrumb link)

See how the URL is `http://localhost:3000/women/tops-women/women/tops-women/tees-women.html` instead of `http://localhost:3000/women/tops-women/tees-women.html`

**Expected behavior**
It should load the product page.

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Chrome
 - Version: 69

**Additional context**
~~Looks like the links are "appending" its href value to the current URL somehow, at first I though it was because the `to` prop in the links where missing the opening `/` but even after adding it the links were still pointing to the wrong URL even though it looks fine on the React Chrome tools.~~

After some digging the problem seems to be that links are using relative URLs instead of absolute.

**Comment by jahvi** [comment]
Never mind I might have had a caching issue, adding a `/` to the beginning of the link seems to fix the issue.

Looks like there's a few other places where the `urlPath` to the product is used like this as well (like the product grid), if this is an acceptable fix I can submit a PR.

**Comment by mateuszwozniak** [comment]
We'll take a look at that as we've already seen such problem. We'll keep you updated on that.
