### ISSUE TITLE
eslint config is missing in ejected client

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#628]
**Describe the bug**
Currently the `eslint` script in the client/package.json can not be used because there is no eslint config anywhere.

**To Reproduce**
1. Go to 'client'
1. Run `yarn eslint`
1. See error

**Expected behavior**
An eslint config file should be found and eslint should be running.

```shell
yarn lint
yarn run v1.19.0
$ eslint ./

Oops! Something went wrong! :(

ESLint: 6.1.0.

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /home/druf/Schreibtisch/projects/pwa/client and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint

error Command failed with exit code 2.
```

**Comment by DanielRuf** [comment]
313af512d298a6f45cfa971a8291206287cf13d0 is the commit which removed it.

**Comment by tutok** [comment]
@DanielRuf did you find also this PR https://github.com/deity-io/falcon/pull/506 ?

**Comment by DanielRuf** [comment]
Not sure why you would want to remove it =)

I see this PR for the first time now.

This should be probably asked when creating the project. Not sure if there was an option for this. Normally I check all the scripts and see if we can use them for our CI.

**Comment by DanielRuf** [comment]
Because for eslint it is not "optional" as you can see in the error message ;-)

**Comment by tutok** [comment]
so what is your opinion, should we have or should not we have eslint configured?

we received a lot of feedback that people do not like eslint at all, and they asking constantly how to turn it off 🤷‍♂.

I think we should also remove this line https://github.com/deity-io/falcon/blob/2e5d478804c60240a8c186b818ad722af6d2bb6b/examples/shop-with-blog/client/package.json#L18 to fix your issue, thanks.

**Comment by DanielRuf** [comment]
> we received a lot of feedback that people do not like eslint at all, and they asking constantly how to turn it off man_shrugging.

In which cases did they have issues or was there something automatically running it?
Why exactly do they not like it and what do they use instead? No linting is not really a solution?

For me as a developer working on a falcon project it makes sense to adjust our code after your codestyle and follow it. This results in cleaner code and less bugs.


> I think we should also remove this line
> 
> https://github.com/deity-io/falcon/blob/2e5d478804c60240a8c186b818ad722af6d2bb6b/examples/shop-with-blog/client/package.json#L18

Probably, yes.

**Comment by cane-lagerwaard** [comment]
@DanielRuf we got some feedback a while ago from users that had their own linting rules. As their team(s) followed these rules strictly for every project, they felt like they were forced to follow the config set by Falcon, so they wanted to use their own

**Comment by cane-lagerwaard** [comment]
@DanielRuf we agree with your approach, which will also make it way easier to create "compatible" PR's

**Comment by DanielRuf** [comment]
Hm, why not name it `.eslintrc.dist` and use `"lint": "eslint -c ./eslintrc.dist ./",`?

**Comment by tutok** [comment]
@DanielRuf can you please elaborate above? what it will give use, eslint will be still configured in the example project.

>In which cases did they have issues or was there something automatically running it?
Why exactly do they not like it and what do they use instead? No linting is not really a solution?

previously our defaults [eslint-config-falcon](https://github.com/deity-io/falcon/tree/dev/packages/falcon-dev-tools/eslint-config-falcon) were used (no `.eslintrc were needed`), but if you did not like it, you could add `.eslintrc` yourself, with your configuration which, could totally overwrite our default.
Also, as you may already realize, we have `eslint-loader` - people did not like that combination.

**Comment by DanielRuf** [comment]
> @DanielRuf can you please elaborate above? what it will give use, eslint will be still configured in the example project.

Using a different filename does not automatically run eslint.

**Comment by DanielRuf** [comment]
The only thing that I do not like and often breaks markup is prettier ;-)
