### ISSUE TITLE
Recommended way to generate icons

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#631]
**What should be changed/improved?**
Currently there are icons in src/assets/icons of the shop demo with the blog.

What do you recommend to generate these?

**Your suggested solution**
A part in the documentation to generate the needed icons.

**Comment by DanielRuf** [comment]
For example I have used https://github.com/itgalaxy/favicons so far.

**Comment by EddyVinck** [comment]
I have used [svgr](https://www.smooth-code.com/open-source/svgr/docs/cli/) to generate icons from SVGs for https://deity.io. 

This was my NPM script for https://boxicons.com, for example.

```
"icons:box": "svgr -d ./src/assets/icons/box-icons-components ./src/assets/icons/box-icons --icon --replace-attr-values '#000=currentColor'"
```
They also have a [Webpack plugin](https://www.smooth-code.com/open-source/svgr/docs/webpack/#webpack) you could try.
