### ISSUE TITLE
adyen-cse-web is deprecated

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#637]
**What should be changed/improved?**
We should migrate adyen-cse-web to the new API using Secure Fields:

https://www.npmjs.com/package/adyen-cse-web

**Your suggested solution**
https://docs.adyen.com/checkout/api-only

**Comment by Borales** [comment]
@DanielRuf thanks :) we this migration planned for the upcoming months.

**Comment by macabeus** [comment]
Is there some news about that?
I checked the code and we are still suing `adyen-cse-web`: https://github.com/deity-io/falcon/blob/793ec503b2bab5440c1f5660a55f5e4780e8d9d1/packages/payment/falcon-adyen-plugin/src/AdyenCCPlugin.tsx#L4

**Comment by hobadams** [comment]
> Is there some news about that?
> I checked the code and we are still suing `adyen-cse-web`:
> 
> https://github.com/deity-io/falcon/blob/793ec503b2bab5440c1f5660a55f5e4780e8d9d1/packages/payment/falcon-adyen-plugin/src/AdyenCCPlugin.tsx#L4

Hey @macabeus, our road map has changed and we won't be looking at this internally for the foreseeable.  We can offer support via our slack channel (https://deity-community.slack.com/archives/CDL2XDSHZ) if you want to try to make the change yourself.
