### ISSUE TITLE
"selected" support for DropdownMenuItem component

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#643]
**What should be changed/improved?**
The DropdownMenuItem component lacks a `selected` option.

**Your suggested solution**
Not sure if this is already possible but I found no relevant information. It would be great to have some support for `selected` to display the currently selected option differently.

**Comment by EddyVinck** [comment]
@DanielRuf I'm not 100% sure, but I just checked the docs for the Dropdown component and it seems the `initial` prop on the `Value` component might be able to help you with this.

https://falcon-ui.docs.deity.io/components-dropdown

```
<Box css={{ height: 150 }}>
  <Value initial="acending">
    {({ value, set }) => (
      <Dropdown onChange={set}>
        <DropdownLabel>Sort by: {value}</DropdownLabel>
        <DropdownMenu>
          <DropdownMenuItem value="ascending">Ascending</DropdownMenuItem>
          <DropdownMenuItem value="descending">Descending</DropdownMenuItem>
        </DropdownMenu>
      </Dropdown>
    )}
  </Value>
</Box>
```

Does this solve your issue?

**Comment by DanielRuf** [comment]
Ah ok, so we have to wrap the value component and set the initial. Not so convenient and as native as `selected` in the items but as far as this works this should be fine.
