### ISSUE TITLE
Sign-in "next" value is not being respected

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#673]
**Describe the bug**
After submitting Login credentials on `http://localhost:3000/sign-in?next=%2Faccount%2Forders` - the user doesn't get redirected to `/account/order` (defined in`?next=` query string), but instead - to Homepage.

**Comment by EddyVinck** [comment]
I'm going to try to fix this

**Comment by EddyVinck** [comment]
@Borales sometimes the solution is simpler than you would think :sweat_smile: 

See: https://github.com/deity-io/falcon/pull/689

I'd like to discuss this approach with you first, so it's still a draft PR.

**Comment by Borales** [comment]
@EddyVinck thanks, I'll check the code 👍
