### ISSUE TITLE
deity/falcon-server does not support NodeJS 8 anymore

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#724]
**Describe the bug**
Currently the falcon-server does not support NodeJS 8 anymore as the optional catch binding is used there. See https://node.green/#ES2019-misc-optional-catch-binding

**To Reproduce**
1. Install the example with server and client
2. use NodeJS 8 and install the dependencies with yarn
* start the application / check the code

**Expected behavior**
There should be no error.

https://github.com/deity-io/falcon/blob/ddfb3259e225dcb1f92a6d8b91c297691db618a1/packages/falcon-server/src/containers/ExtensionContainer.ts#L260

https://stackoverflow.com/a/56001361/753676

**Comment by Borales** [comment]
@DanielRuf Hi. Thanks for this report. I wonder how it got passed our tests on Node 8.

This should be fixed by https://github.com/deity-io/falcon/pull/725
