### ISSUE TITLE
Feature: configurable category ID for HomeProducts

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#740]
**Is your feature request related to a problem? Please describe.**
The category ID in the HomeProducts component is hardcoded.

**Describe the solution you'd like**
It would be good to have it dynamic, depending on the config (dev, stage, prod).

**Describe alternatives you've considered**
Make it configurable in the Magento module.

**Comment by Borales** [comment]
Hi @DanielRuf 

The given example application is simply a showcase of how such Queries can be used to fetch the data on the FalconClient side, so it's up to the project itself to decide how to implement it.

There're several ways how you could fetch the products:

- through the Category type (`Category.productList` field) - but you need to know the exact category ID before sending this Query (currently used in the example app)
- through `productList` query (filtering the products with a specific attribute value, like `showOnHomepage: 1` or something like that)
- through your custom logic (using the FS config or remote Magento settings) that needs to be added to your API resolver/Custom Extension manually - and exposed as a new Query field, like:
```graphql
extend type Query {
  homepageProducts: ProductList
}
``` 
- or even though a custom Magento endpoint in your custom API resolver (like in the previous item)

We covered only the most generic/commonly used ones (first 2 from the list above), leaving custom options to the end-developers.
