### ISSUE TITLE
Demo site theme

### ISSUE THREAD

**Issue by malasaad82** [deity-io/falcon#775]
Hi,
Thanks for this project. I just wonder how could I get the same theme that is used on demo site 
https://demo.deity.io/  ?

I tried to install by using clone and create command but its not same theme. any way to get demo theme ?
Thanks

**Comment by hobadams** [comment]
Hey @malasaad82,

The example app used on demo.deity.io is available through Falcon Platform, our paid service.

If you're interested you can [contact our team](https://deity.io/contact) and they will help you get started.

We are in the process of updating our docs, it will make this much clearer as well as highlighting the differences between Falcon Open Source and Falcon Platform.

If you have any other questions / queries feel free to ask. We have a #help channel in our [community slack channel](https://deity-community.slack.com/archives/CDL2XDSHZ) that might be a better platform if you want a quick response :-)
