### ISSUE TITLE
Improve import statements readability

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon#91]
**What should be changed/improved?**
Improve import readability

![image](https://user-images.githubusercontent.com/40865297/47284344-55e47f80-d5e7-11e8-8317-de37c1396ecd.png)

**Your suggested solution**
Change the order into the following:

```
import A from 'package';
import B from 'other-package';

import C from '@org/package';
import D from '@org/package-two';

import E from 'src/component';
import F from 'src/other-component';
```

Becomes something like this:
![image](https://user-images.githubusercontent.com/40865297/47284853-259de080-d5e9-11e8-9929-06160e585e5c.png)

**Comment by tutok** [comment]
resolved by https://github.com/deity-io/falcon/pull/495
